import Head from "next/head"
import Image from "next/image"

import illustration from "../public/illustration-hero.svg"
import icon from "../public/icon-music.svg"

export default function Home() {
  return (
    <div className="flex items-center justify-center h-screen p-0 m-0 bg-no-repeat bg-contain bg-paleBlue font-redHat bg-mobile-background md:bg-desktop-background">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-5">
        <div
          id="card"
          className="flex flex-col items-center justify-center max-w-md min-w-0 bg-white shadow-2xl rounded-3xl"
        >
          <Image src={illustration} alt="" className="rounded-t-3xl" />
          <div className="flex flex-col items-center justify-center p-10">
            <h1 className="text-xl font-black ">Order Summary</h1>
            <p className="mt-5 font-normal text-center text-desaturatedBlue">
              You can now listen to millions of songs, audiobooks, and podcasts
              on any device anywhere you like!
            </p>
            <div className="flex items-center justify-around w-full mt-10">
              <div className="flex gap-5 ">
                <Image src={icon} alt="" />
                <div>
                  <p className="font-black">Annual Plan</p>
                  <p className="text-desaturatedBlue">$59.99/year</p>
                </div>
              </div>
              <a
                href="#"
                className="font-black underline text-darkBlue hover:text-brightBlueHover"
              >
                Change
              </a>
            </div>
            <a
              href="#"
              className="w-full p-3 mt-10 text-center text-white shadow-xl rounded-xl bg-brightBlue hover:bg-brightBlueHover"
            >
              Proceed to Payment
            </a>
            <a
              href="#"
              className="p-3 mt-5 font-black text-desaturatedBlue hover:text-darkBlue"
            >
              Cancel Order
            </a>
          </div>
        </div>
      </main>
    </div>
  )
}
